### ISSUE TITLE
Double header bar

### ISSUE THREAD

**Issue by Eijebong** [vinszent/gnome-twitch#239]
Steps to reproduce:
 - When watching a stream, go full screen by clicking the full screen button in the header bar (or double click)
 - Get out of full screen via i3 (mod+f)
 - Enjoy the second header bar when hovering the first one :)

[Screenshot of the bug](https://img.bananium.fr/eijebong/3f89fa8d-08b6-41f4-ac88-938ec9480845.png)

**Comment by vinszent** [comment]
Does mod+f send the proper fullscreen events to the window? My experience with tiling wms is that some of them just "maximise" the window and don't actually fullscreen it. I'll try investigate during the week.

**Comment by Eijebong** [comment]
Gnome-twitch is the only app I know that misbehaves.
How can I check that mod+f sends the correct events ?

**Comment by vinszent** [comment]
Ok if it's only GT not working then it's probably a bug in my code.

**Comment by cra0zy** [comment]
Well the problem is obviously that one headerbar wasn't enough to hold the awesomeness of this application so a second one was needed :P

**Comment by vinszent** [comment]
@cra0zy Can you check whether it's been fixed now?

**Comment by cra0zy** [comment]
You probably want @Eijebong to check, I am using GNOME.

**Comment by vinszent** [comment]
Ah my bad, @Eijebong could you please check if it has been fixed?

**Comment by Eijebong** [comment]
When I get home yeah ^^

**Comment by Eijebong** [comment]
Yeah; it's better, you can still see it if you keep your cursor on the header bar while getting back from full screen but it disappears almost immediately.

**Comment by vinszent** [comment]
@Eijebong Ok good, I can probably tweak that later, I just need to turn the animation off when going from fullscreen.
