### ISSUE TITLE
Is there a specific reason for setting gtk+-3.0 >= 3.20?

### ISSUE THREAD

**Issue by patraanjan23** [vinszent/gnome-twitch#273]
I just wanted to build it with linux mint 18.1 (ubuntu 16.04 base) which has 3.18 of gtk+-3.0 kit. I changed the meson.build requirement to match 3.18 and built the package successfully. It's working fine. I just wanted to if the project uses any specific 3.20 feature?

**Comment by vinszent** [comment]
I can't remember exactly, but I think it had to do with some new CSS rules/styling that had been introduced in 3.20.

**Comment by patraanjan23** [comment]
Alright. I checked the gnome 3.20 release notes. It indeed is related to
gtk css theming.

The reason I opened this issue is because a lot of users are using ubuntu
16.04 LTS based distribution, which probably does not come with 3.20. they
are stuck with the 0.2.x version of gnome-twitch, which is very old and
bugged. So there are 2 options now, if the ppa maintainer changed the
meson.build to require 3.18 for the xenial branch or someone can make a
simple script for building from source.

**Comment by jangernert** [comment]
You can use the flatpak on Ubuntu 16.04 without any problems ;)
The required Gtk+ version will be provided by the gnome-runtime. The only possible downside I can think of right now is: flaptaks currently ignore the gtk theme and default to adwaita.

**Comment by TingPing** [comment]
Themes should be solved in Flatpak relatively soon at least.

**Comment by jangernert** [comment]
@TingPing any idea how that will be solved? A separate theme for each runtime? Newer Gtk+ versions won't support themes on the host-system of a Ubuntu 16.04 installation with Gtk+ 3.18.

**Comment by TingPing** [comment]
@jangernert There is an extension point for Gtk themes now and they will have to be packaged. Pulling in from the host won't happen because as you say it requires specific versions that they probably don't have anyway *and* some toolkits (Qt) still have binary themes.

**Comment by h1z1** [comment]
Welcome to the mess that is Ubuntu.. *sigh*  Fap-pak doesn't solve anything.   There are very few (which ?) distros that ship with GTK3.5

**Comment by TingPing** [comment]
> Welcome to the mess that is Ubuntu.. sigh Fap-pak doesn't solve anything. There are very few (which ?) distros that ship with GTK3.5

I'm not sure if that was supposed to be a joke but yes Flatpak solves it as it will have the latest Gtk bundled. Also most distributions are more up to date than Ubuntu LTS and have 3.20 by now.

@jangernert By the way I packaged some themes today including `org.gtk.Gtk3theme.Ambiance` in [flathub](https://flathub.org) for Ubuntu.

**Comment by h1z1** [comment]
Entirely for another forum, not entirely sure you understand what it is?   I wasn't kidding about the comment though.  Thick binaries hide a lot of implementation details.   What libs are used, licenses, etc.   You're quite welcome to limit your application to it.

I commented in this because GTK prevented me from using your app.  CentOS 7.

**Comment by jangernert** [comment]
> I commented in this because GTK prevented me from using your app. CentOS 7.

So everything should be written in C using Motif to ensure it works on ancient operating systems?
And by the way, flatpak does solve exactly this problem. There are experimental flatpak builds for RHEL 7
https://copr.fedorainfracloud.org/coprs/amigadave/flatpak-epel7/
With them you should be able to install the required gnome-runtime and gnome-twitch no problem.
The gnome-runtime will not interfere with the Gtk+ version your distro ships.

**Comment by h1z1** [comment]
CentOS 7 is ancient?   Interesting.    If SunOS was still maintained Solaris wouldn't have happened either.    I guess yes?  GTK3 would be properly installed in a system wide directory like /opt not buried.  Funny thing about UNIX and backward compatibility.

Regarding the EPEL build, given the target of RHEL/CentOS is stability over bleeding edge, anyone installing experimental code in it is insane.

I'm not entirely sure we're reading the same requirements.  Installing failpak requires quite a bit.  http://docs.flatpak.org/en/latest/introduction.html#under-the-hood ?

I agree the gnome runtime shouldn't impact other versions.  All I'm saying is anyone whose ever dealt with every other attempt to make build once run everywhere packaging systems (java jar, war, webstart, flash, etc), knows the hell that awaits.   fapak is trying to solve a problem that isn't there.  It's not even trying to use RECENT build environments but replacing them.

**Comment by TingPing** [comment]
> CentOS 7 is ancient? Interesting. 

In consumer software, yes. For a desktop application developer, yes.

> Regarding the EPEL build, given the target of RHEL/CentOS is stability over bleeding edge, anyone installing experimental code in it is insane.

If you go in expecting very old software then that is fine. Your issue is you want to use the latest software on it.

> I'm not entirely sure we're reading the same requirements. Installing failpak requires quite a bit. http://docs.flatpak.org/en/latest/introduction.html#under-the-hood ?

Yes it has a few dependencies, CentOS 7 has most of them. If you want to be taken seriously I would suggest acting like an adult and not calling projects childish names.

**Comment by h1z1** [comment]
>>    CentOS 7 is ancient?

> In consumer software, yes. For a desktop application developer, yes.

Thankfully that is not a shared opinion.


>>    Regarding the EPEL build, given the target of RHEL/CentOS is stability over bleeding edge, anyone installing experimental code in it is insane.

> If you go in expecting very old software then that is fine. Your issue is you want to use the latest software on it.

Guess that depends what you're considering very old and your understanding of release management.

>>    I'm not entirely sure we're reading the same requirements. Installing failpak requires quite a bit. http://docs.flatpak.org/en/latest/introduction.html#under-the-hood ?

> Yes it has a few dependencies, CentOS 7 has most of them. If you want to be taken seriously I would suggest acting like an adult and not calling projects childish names.

What?  Interesting selective use of quoting.   The comment was in response to @jangernert above: 

> So everything should be written in C using Motif to ensure it works on ancient operating systems?
> And by the way, flatpak does solve exactly this problem. There are experimental flatpak builds for RHEL 7

I'm not entirely sure what it is you're even claiming let alone responding to.    His comment was regarding C and Motif - two standards.  I never stated older versions needed to be maintained indefinitely.   Their implementation is documented and well understood however.

Adults take constructive criticism.  I get the impression you're not exposed to that often.
